# Generated by Django 3.2.5 on 2021-08-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainCRUD', '0003_auto_20210806_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
