# Generated by Django 3.2.5 on 2021-08-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCRUD', '0004_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
