# Generated by Django 3.2.5 on 2021-08-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainCRUD', '0005_contacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Correo',
        ),
    ]
