# Generated by Django 3.2.5 on 2021-08-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainCRUD', '0005_correo'),
        ('mainCRUD', '0006_rename_contacto_correo'),
    ]

    operations = [
    ]
